spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aegis_monitor?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: change-me
  sql:
    init:
      mode: always

aegis:
  agent:
    register-token: demo-register-token
